apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: tomcat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: saikalyan551/devproject:latest
        ports:
        - containerPort: 8080

