---
- hosts: tomcat-nodes 
  become: true
  become_method: sudo       # Set become method
  remote_user: ubuntu
  tasks: 
    - name: copy war into tomcat server
      copy: 
        src: /home/ubuntu/artifacts 
        dest: /home/ubuntu/



